# IC2 Task 5B server properties
level-name=world_ic2_task5b
server-port=25569
rcon.port=25579
rcon.password=test123
enable-rcon=true
enable-command-block=true
online-mode=false
spawn-protection=0
motd=IC2 Task 5B Materialization
