#Minecraft server properties
#Sat Jan 31 23:30:54 CET 2026
view-distance=10
max-build-height=256
server-ip=
level-seed=
rcon.port=25579
server-port=25569
allow-nether=true
enable-command-block=true
gamemode=1
enable-rcon=true
op-permission-level=4
enable-query=false
generator-settings=
resource-pack=
level-name=world
rcon.password=test123
player-idle-timeout=0
motd=EditKit Test Server
announce-player-achievements=true
force-gamemode=false
white-list=false
pvp=true
spawn-npcs=true
spawn-animals=true
generate-structures=true
snooper-enabled=true
difficulty=1
level-type=DEFAULT
spawn-monsters=true
max-players=10
spawn-protection=0
online-mode=false
allow-flight=true
