#Minecraft server properties
#Sat Jan 31 14:00:15 CET 2026
view-distance=10
max-build-height=256
server-ip=127.0.0.1
level-seed=
gamemode=1
enable-command-block=true
allow-nether=true
server-port=25565
enable-rcon=false
enable-query=false
op-permission-level=4
generator-settings=
resource-pack=
level-name=world_spiral_test
player-idle-timeout=0
motd=Minecraft 1.7.10 Test Server
announce-player-achievements=true
force-gamemode=false
hardcore=false
white-list=false
pvp=false
spawn-npcs=true
spawn-animals=true
generate-structures=false
snooper-enabled=false
difficulty=1
level-type=DEFAULT
spawn-monsters=true
max-players=10
spawn-protection=0
online-mode=false
allow-flight=true
