#Minecraft server properties
#Sat Jan 31 18:51:53 CET 2026
generator-settings=
op-permission-level=4
allow-nether=true
level-name=spiral_y100
enable-query=false
allow-flight=true
announce-player-achievements=true
server-port=25568
level-type=DEFAULT
enable-rcon=false
level-seed=
force-gamemode=false
server-ip=
max-build-height=256
spawn-npcs=true
white-list=false
spawn-animals=true
snooper-enabled=true
online-mode=false
resource-pack=
pvp=true
difficulty=1
enable-command-block=true
gamemode=1
player-idle-timeout=0
max-players=10
spawn-monsters=true
view-distance=10
generate-structures=true
spawn-protection=0
motd=A Minecraft Server
