# Railcraft Task 5B server properties
level-name=world_railcraft_task5b
server-port=25571
rcon.port=25581
rcon.password=test123
enable-rcon=true
enable-command-block=true
online-mode=false
spawn-protection=0
motd=Railcraft Task 5B Materialization
