# -*- coding: utf-8 -*-
import os

out_path = "src/converters/mrcrayfish_furniture/ANALIZA_BLOKOW_TE_ZADANIE1.md"

lines = []

def add(text):
    lines.append(text)

add("# Analiza blokow i Tile Entities – MrCrayfish Furniture Mod")
add("")
add("## Cel zadania")
add("Zidentyfikowac wszystkie bloki, tile entities (TE) i ich wlasciwosci w MrCrayfish Furniture Mod w wersjach 1.7.10 oraz 1.18.2, aby zbudowac konwerter mapujacy swiat.")
add("")
add("## Zrodla")
add("- **1.7.10 (source):** MrCrayfishFurnitureMod.java, pakiety com.mrcrayfish.furniture.tileentity.*")
add("- **1.18.2 (target):** ModBlocks.java, ModBlockEntities.java, pakiety com.mrcrayfish.furniture.blockentity.*")
add("")
add("---")
add("")
add("## 1. Rejestracja blokow – porownanie 1.7.10 vs 1.18.2")
add("")
add("### 1.1 Bloki zarejestrowane w 1.7.10")
add("")
add("W MrCrayfishFurnitureMod.java bloki rejestrowane sa przez:")
add("```")
add("GameRegistry.registerBlock(block, block.func_149739_a().substring(5));")
add("```")
add("")
add("| Lp | Nazwa rejestru (ID) | Klasa bloku | Uwagi |")
add("|----|---------------------|-------------|-------|")
add("| 1  | lampon | BlockLampOn | Lampka wlaczona |")
add("| 2  | lampoff | BlockLampOff | Lampka wylaczona |")
add("| 3  | coffetablewood | BlockCoffeeTable | Stolik kawowy (drewno) |")
add("| 4  | coffetablestone | BlockCoffeeTable | Stolik kawowy (kamien) |")
add("| 5  | tablewood | BlockTable | Stol (drewno) |")
add("| 6  | tablestone | BlockTable | Stol (kamien) |")
add("| 7  | chairwood | BlockChair | Krzeslo (drewno) |")
add("| 8  | chairstone | BlockChair | Krzeslo (kamien) |")
add("| 9  | freezer | BlockFreezer | Zamrazarka (dolna czesc lodowki) |")
add("| 10 | fridge | BlockFridge | Lodowka (gorna czesc) |")
add("| 11 | cabinet | BlockCabinet | Szafka |")
add("| 12 | couch | BlockCouch | Sofa (z podtypami kolorow) |")
add("| 13 | blinds | BlockBlinds | Rolety (otwarte) |")
add("| 14 | blindsclosed | BlockBlindsClosed | Rolety (zamkniete) |")
add("| 15 | curtains | BlockCurtains | Zaslony |")
add("| 16 | curtainsoff | BlockCurtainsOff | Zaslony wylaczone |")
add("| 17 | bedsidecabinet | BlockBedsideCabinet | Szafka nocna |")
add("| 18 | oven | BlockOven | Piekarnik |")
add("| 19 | ovenoverhead | BlockOvenOverhead | Okap nad piekarnikiem |")
add("| 20 | microwave | BlockMicrowave | Kuchenka mikrofalowa |")
add("| 21 | computer | BlockComputer | Komputer |")
add("| 22 | printer | BlockPrinter | Drukarka |")
add("| 23 | tv | BlockTV | Telewizor |")
add("| 24 | stereo | BlockStereo | Stereo / radio |")
add("| 25 | washingmachine | BlockWashingMachine | Pralka |")
add("| 26 | dishwasher | BlockDishwasher | Zmywarka |")
add("| 27 | mailbox | BlockMailBox | Skrzynka pocztowa |")
add("| 28 | bin | BlockBin | Kosz na smieci |")
add("| 29 | toaster | BlockToaster | Toster |")
add("| 30 | blender | BlockBlender | Blender |")
add("| 31 | plate | BlockPlate | Talerz |")
add("| 32 | cup | BlockCup | Kubek |")
add("| 33 | counterdoored | BlockCounterDoored | Szafka kuchenna (z drzwiami) |")
add("| 34 | countersink | BlockCounterSink | Zlew kuchenny |")
add("| 35 | kitchencabinet | BlockKitchenCabinet | Szafka kuchenna |")
add("| 36 | choppingboard | BlockChoppingBoard | Deska do krojenia |")
add("| 37 | barstool | BlockBarStool | Stolek barowy |")
add("| 38 | cookiejar | BlockCookieJar | Sloik na ciastka |")
add("| 39 | present | BlockPresent | Prezent |")
add("| 40 | tree | BlockTree | Dekoracyjne drzewko |")
add("| 41 | bath1 | BlockBath | Wanna (czesc 1) |")
add("| 42 | bath2 | BlockBath | Wanna (czesc 2) |")
add("| 43 | showerbottom | BlockShowerBottom | Prysznic (dol) |")
add("| 44 | showertop | BlockShowerTop | Prysznic (gora) |")
add("| 45 | showerheadoff | BlockShowerHeadOff | Glowka prysznicowa (wylaczona) |")
add("| 46 | showerheadon | BlockShowerHeadOn | Glowka prysznicowa (wlaczona) |")
add("| 47 | basin | BlockBasin | Umywalka |")
add("| 48 | wallcabinet | BlockWallCabinet | Szafka scienna |")
add("| 49 | birdbath | BlockBirdBath | Poidlo dla ptakow |")
add("| 50 | stonepath | BlockStonePath | Kamienna sciezka |")
add("| 51 | whitefence | BlockWhiteFence | Bialy plot |")
add("| 52 | tap | BlockTap | Kran |")
add("| 53 | electricfence | BlockElectricFence | Elektryczne ogrodzenie |")
add("| 54 | doorbell | BlockDoorbell | Dzwonek do drzwi |")
add("| 55 | firealarmoff | BlockFireAlarmOff | Alarm przeciwppozarowy (wylaczony) |")
add("| 56 | firealarmon | BlockFireAlarmOn | Alarm przeciwppozarowy (wlaczony) |")
add("| 57 | ceilinglightoff | BlockCeilingLightOff | Swiatlo sufitowe (wylaczone) |")
add("| 58 | ceilinglighton | BlockCeilingLightOn | Swiatlo sufitowe (wlaczone) |")
add("| 59 | toilet | BlockToilet | Toaleta |")
add("| 60 | hedge | BlockHedge | Zywoplot |")
add("| 61 | hey | BlockHey | Dekoracyjny blok Hey |")
add("| 62 | nyan | BlockNyan | Dekoracyjny blok Nyan |")
add("| 63 | pattern | BlockPattern | Wzorzysty blok dekoracyjny |")
add("| 64 | yellowglow | BlockYellowGlow | Zolty blok swiecacy |")
add("| 65 | whiteglass | BlockWhiteGlass | Biale szklo dekoracyjne |")
add("")
add("**Liczba blokow:** ~65+")
add("")
add("**Uwagi:** Niektore bloki wystepuja w parach on/off. freezer i fridge tworza wieloblok. bath1/bath2 i showerbottom/showertop tworza wielobloki. couch uzywa metadanych dla kolorow (16 kolorow welny).")
add("")
add("### 1.2 Bloki zarejestrowane w 1.18.2")
add("")
add("W ModBlocks.java uzywany jest DeferredRegister z ResourceLocation.")
add("")
add("Przyklady blokow (warianty materialowe i kolorowe):")
add("- Stoly: oak_table, spruce_table, birch_table, jungle_table, acacia_table, dark_oak_table, crimson_table, warped_table, stripped_oak_table, ..., stone_table, granite_table, diorite_table, andesite_table")
add("- Krzesla: oak_chair, spruce_chair, ..., stone_chair, granite_chair, ...")
add("- Stoliki kawowe: oak_coffee_table, ..., stone_coffee_table, ...")
add("- Sofy: white_sofa, orange_sofa, ..., black_sofa (16 kolorow barwnikow)")
add("- Szafki: oak_cabinet, spruce_cabinet, ..., stone_cabinet, granite_cabinet, ...")
add("- Szafki nocne: oak_bedside_cabinet, ...")
add("- Biurka: oak_desk, ..., stone_desk, ...")
add("- Szafki pod biurko: oak_desk_cabinet, ...")
add("- Skrzynki: oak_crate, ...")
add("- Lawki parkowe: oak_park_bench, ...")
add("- Rolety: oak_blinds, ...")
add("- Zaslony: oak_curtains, ...")
add("- Ogrodzenia upgraded: oak_upgraded_fence, oak_upgraded_gate, ...")
add("- Plotki: white_picket_fence, ..., orange_picket_fence, ... (16 kolorow)")
add("- Furtka plotkowa: white_picket_gate, ... (16 kolorow)")
add("- Skrzynki pocztowe: oak_mail_box, ...")
add("- Trampoliny: oak_trampoline, ...")
add("- Coolery: white_cooler, orange_cooler, ... (16 kolorow)")
add("- Grille: white_grill, orange_grill, ... (16 kolorow)")
add("- Deska do nurkowania: oak_diving_board")
add("- Wycieraczki: oak_door_mat, ...")
add("- Blaty kuchenne: white_kitchen_counter, ... (16 kolorow)")
add("- Szuflady kuchenne: white_kitchen_drawer, ... (16 kolorow)")
add("- Zlewy kuchenne: white_kitchen_sink, ... (16 kolorow)")
add("- Kamienna sciezka: rock_path")
add("- Zywoploty: oak_hedge, ... (warianty lisci)")
add("- Lodowki: fridge_light, fridge_dark")
add("- Zamrazarki: freezer_light, freezer_dark")
add("")
add("**Liczba blokow:** ~300+ (wliczajac warianty materialow i kolorow)")
add("")
add("**Kluczowe roznice:**")
add("- W 1.18.2 kazdy material (oak, spruce, stone, granite, itd.) to osobny blok")
add("- Dodano nowe bloki: crate, desk, desk_cabinet, park_bench, upgraded_fence/gate, picket_fence/gate, trampoline, cooler, grill, diving_board, door_mat, kitchen_counter/drawer/sink, rock_path")
add("- USUNIETE z 1.18.2: Oven, Microwave, Computer, Printer, TV, Stereo, WashingMachine, Dishwasher, Toilet, Basin, Bath, Shower, ShowerHead, WallCabinet, BirdBath, StonePath, Tap, ElectricFence, FireAlarm, CeilingLight, Lamp, Tree, Present, Toaster, Blender, Plate, Cup, ChoppingBoard, BarStool, CookieJar, CounterDoored, CounterSink")

add("")
add("---")
add("")
add("## 2. Rejestracja Tile Entities / Block Entities – porownanie")
add("")
add("### 2.1 Tile Entities w 1.7.10")
add("")
add("W MrCrayfishFurnitureMod.java rejestracja przez:")
add("```")
add('GameRegistry.registerTileEntity(TileEntityOven.class, "cfmOven");')
add("```")
add("")
add("| Lp | Nazwa TE (ID) | Klasa | Opis |")
add("|----|---------------|-------|------|")
add("| 1  | cfmOven | TileEntityOven | Piekarnik |")
add("| 2  | cfmFridge | TileEntityFridge | Lodowka |")
add("| 3  | cfmCabinet | TileEntityCabinet | Szafka |")
add("| 4  | cfmFreezer | TileEntityFreezer | Zamrazarka |")
add("| 5  | cfmBedsideCabinet | TileEntityBedsideCabinet | Szafka nocna |")
add("| 6  | cfmMailBox | TileEntityMailBox | Skrzynka pocztowa |")
add("| 7  | cfmComputer | TileEntityComputer | Komputer |")
add("| 8  | cfmPrinter | TileEntityPrinter | Drukarka |")
add("| 9  | cfmTV | TileEntityTV | Telewizor |")
add("| 10 | cfmStereo | TileEntityStereo | Stereo |")
add("| 11 | cfmPresent | TileEntityPresent | Prezent |")
add("| 12 | cfmBin | TileEntityBin | Kosz |")
add("| 13 | cfmWallCabinet | TileEntityWallCabinet | Szafka scienna |")
add("| 14 | cfmBath | TileEntityBath | Wanna |")
add("| 15 | cfmBasin | TileEntityBasin | Umywalka |")
add("| 16 | cfmShowerHead | TileEntityShowerHead | Glowka prysznicowa |")
add("| 17 | cfmCookieJar | TileEntityCookieJar | Sloik na ciastka |")
add("| 18 | cfmPlate | TileEntityPlate | Talerz |")
add("| 19 | cfmCouch | TileEntityCouch | Sofa (kolor) |")
add("| 20 | cfmToaster | TileEntityToaster | Toster |")
add("| 21 | cfmChoppingBoard | TileEntityChoppingBoard | Deska do krojenia |")
add("| 22 | cfmBlender | TileEntityBlender | Blender |")
add("| 23 | cfmMicrowave | TileEntityMicrowave | Mikrofalowka |")
add("| 24 | cfmWashingMachine | TileEntityWashingMachine | Pralka |")
add("| 25 | cfmDishwasher | TileEntityDishwasher | Zmywarka |")
add("| 26 | cfmCabinetKitchen | TileEntityCabinetKitchen | Szafka kuchenna |")
add("| 27 | cfmCounterSink | TileEntityCounterSink | Zlew kuchenny |")
add("| 28 | cfmCup | TileEntityCup | Kubek |")
add("")
add("**Liczba TE:** 28")
add("")
add("### 2.2 Block Entities w 1.18.2")
add("")
add("W ModBlockEntities.java:")
add("```")
add('public static final RegistryObject<BlockEntityType<CabinetBlockEntity>> CABINET = register("cabinet", CabinetBlockEntity::new, () -> new Block[]{...});')
add("```")
add("")
add("| Lp | Nazwa BE (ID) | Klasa | Obslugiwane bloki |")
add("|----|---------------|-------|-------------------|")
add("| 1  | cfm:cabinet | CabinetBlockEntity | oak_cabinet, spruce_cabinet, ..., stone_cabinet |")
add("| 2  | cfm:bedside_cabinet | BedsideCabinetBlockEntity | oak_bedside_cabinet, ... |")
add("| 3  | cfm:desk_cabinet | DeskCabinetBlockEntity | oak_desk_cabinet, ... |")
add("| 4  | cfm:crate | CrateBlockEntity | oak_crate, ... |")
add("| 5  | cfm:mail_box | MailBoxBlockEntity | oak_mail_box, ... |")
add("| 6  | cfm:trampoline | TrampolineBlockEntity | oak_trampoline, ... |")
add("| 7  | cfm:cooler | CoolerBlockEntity | white_cooler, orange_cooler, ... (16 kolorow) |")
add("| 8  | cfm:grill | GrillBlockEntity | white_grill, ... (16 kolorow) |")
add("| 9  | cfm:door_mat | DoorMatBlockEntity | oak_door_mat, ... |")
add("| 10 | cfm:kitchen_drawer | KitchenDrawerBlockEntity | white_kitchen_drawer, ... (16 kolorow) |")
add("| 11 | cfm:kitchen_sink | KitchenSinkBlockEntity | white_kitchen_sink, ... (16 kolorow) |")
add("| 12 | cfm:fridge | FridgeBlockEntity | fridge_light, fridge_dark |")
add("| 13 | cfm:freezer | FreezerBlockEntity | freezer_light, freezer_dark |")
add("")
add("**Liczba BE:** 13")
add("")
add("**Kluczowe roznice:**")
add("- W 1.18.2 BE obsluguja wszystkie warianty materialowe jednego typu")
add("- Brak BE w 1.18.2 dla: Oven, Microwave, Computer, Printer, TV, Stereo, WashingMachine, Dishwasher, Bath, Basin, Shower, WallCabinet, Present, Toaster, Blender, Plate, Cup, ChoppingBoard, CookieJar, CounterSink")

add("")
add("---")
add("")
add("## 3. Szczegolowa analiza Tile Entities – 1.7.10")
add("")
add("### 3.1 TileEntityOven (cfmOven)")
add("- Inventory: ISidedInventory, 18 slotow (ItemStack[] ovenItemStacks = new ItemStack[18])")
add("- Mechanika: Wlasny system przepisow Recipes.getOvenRecipeFromInput()")
add("- Czas gotowania: ovenCookTime inkrementowany, currentItemCookTime = 600 ticks")
add("- NBT: Items (lista slotow), BurnTime (czas palenia), CookTime (postep gotowania)")
add("")
add("### 3.2 TileEntityFridge (cfmFridge)")
add("- Inventory: IInventory, 16 slotow (fridgeContents[16])")
add("- NBT: fridgeItems (lista slotow z fridgeSlot)")
add("")
add("### 3.3 TileEntityCabinet (cfmCabinet)")
add("- Inventory: IInventory, 16 slotow (cabinetContents[16])")
add("- Dzwieki: Otwieranie/zamykanie")
add("- NBT: cabinetItems (lista slotow z cabinetSlot)")
add("")
add("### 3.4 TileEntityFreezer (cfmFreezer)")
add("- Inventory: IInventory (kompan dla lodowki)")
add("- Wieloblok: Wymaga fridge bezposrednio nad soba, w przeciwnym razie niszczy sie")
add("- Drops: Wysypuje itemki przy zniszczeniu")
add("")
add("### 3.5 TileEntityMicrowave (cfmMicrowave)")
add("- Inventory: ISidedInventory, 1 slot (ItemStack item)")
add("- Mechanika: Szybkie gotowanie – 40 ticks")
add("- NBT: Item (zawartosc), Coooking (boolean), Progress (postep)")
add("")
add("### 3.6 TileEntityBlender (cfmBlender)")
add("- Inventory: 4 slotow na skladniki (ingredients[4])")
add("- Mechanika: Mieszanie -> wytwarza 6 napojow, 200 ticks")
add("- NBT: Items, Blending, Progress, DrinkCount, DrinkName, HealAmount, CurrentRed/Green/Blue")
add("")
add("### 3.7 TileEntityPrinter (cfmPrinter)")
add("- Inventory: ISidedInventory, 3 sloty (printerItemStacks[3])")
add("- Mechanika: Drukowanie – zuzywa barwnik lub enchanted book jako tusz")
add("- Czas: 1000 ticks (zwykly barwnik) lub 10000 ticks (enchanted book)")
add("- NBT: Items, PrintTime, PrintingTime")
add("")
add("### 3.8 TileEntityWashingMachine (cfmWashingMachine)")
add("- Inventory: ISidedInventory, 5 slotow (4 na zbroje + 1 na mydlo)")
add("- Mechanika: Naprawia durability zbroi co 50 ticks (20 w trybie super)")
add("- NBT: Items, Washing, SuperMode, Progress, Remaining")
add("")
add("### 3.9 TileEntityDishwasher (cfmDishwasher)")
add("- Inventory: ISidedInventory, 7 slotow (6 na narzedzia + 1 na mydlo)")
add("- Mechanika: Analogiczna do pralki – naprawia narzedzia")
add("- NBT: Items, Washing, SuperMode, Progress, Remaining")
add("")
add("### 3.10 TileEntityMailBox (cfmMailBox)")
add("- Inventory: IInventory, 6 slotow (mailBoxContents[6])")
add("- Wlasciciel: UUID ownerUUID, String ownerName")
add("- Blokada: boolean locked")
add("- NBT: mailBoxItems (mailBoxSlot), OwnerUUID, OwnerName, Locked")
add("")
add("### 3.11 TileEntityBin (cfmBin)")
add("- Inventory: IInventory, 12 slotow (binContents[12])")
add("- NBT: Items (lista slotow)")
add("")
add("### 3.12 TileEntityTV (cfmTV)")
add("- Dane: int channel – numer kanalu TV")
add("- NBT: Channel")
add("- canUpdate() = false")
add("")
add("### 3.13 TileEntityStereo (cfmStereo)")
add("- Dane: ItemStack record, int count")
add("- NBT: RecordItem, Record, count")
add("")
add("### 3.14 TileEntityComputer (cfmComputer)")
add("- Inventory: IInventory, 1 slot (ItemStack paySlot)")
add("- Dane: int stockNum, boolean isTrading")
add("- NBT: StockNum")
add("")
add("### 3.15 TileEntityToaster (cfmToaster)")
add("- Dane: Prosty TE przechowujacy stan opiekania")
add("- NBT: zawiera stan opiekania")
add("")
add("### 3.16 TileEntityCounterSink (cfmCounterSink)")
add("- Dane: boolean hasWater / poziom wody")
add("- NBT: zawiera stan wody")
add("")
add("### 3.17 TileEntityBasin (cfmBasin)")
add("- Dane: poziom wody")
add("- NBT: zawiera stan wody")
add("")
add("### 3.18 TileEntityBath (cfmBath)")
add("- Dane: poziom wody, stan wypelnienia")
add("- NBT: zawiera stan wody")
add("")
add("### 3.19 TileEntityCouch (cfmCouch)")
add("- Dane: int colour – kolor sofy (odpowiada kolorom welny)")
add("- NBT: zawiera kolor")
add("")
add("### 3.20 Pozostale TE (krotki opis)")
add("")
add("| TE | Dane | NBT |")
add("|----|------|-----|")
add("| TileEntityChoppingBoard | Przechowuje noz / skladniki | Items |")
add("| TileEntityPlate | Przechowuje jedzenie na talerzu | Items |")
add("| TileEntityCup | Przechowuje napoj | Items, kolor |")
add("| TileEntityCookieJar | Przechowuje ciastka | Items |")
add("| TileEntityPresent | Przechowuje zawartosc prezentu | Items |")
add("| TileEntityShowerHead | Stan on/off, woda | Stan wody |")
add("| TileEntityWallCabinet | 4-9 slotow (inventory) | Items |")

add("")
add("---")
add("")
add("## 4. Szczegolowa analiza Block Entities – 1.18.2")
add("")
add("### 4.1 BasicLootBlockEntity (bazowa klasa abstrakcyjna)")
add("- Rozszerza: RandomizableContainerBlockEntity, implementuje WorldlyContainer")
add("- Inventory: NonNullList<ItemStack> items")
add("- Otwieranie/zamykanie: ContainerOpenersCounter openersCounter")
add("- NBT: Obsluga przez ContainerHelper.saveAllItems() / loadAllItems()")
add("- Loot tables: Wspiera loot tables (LootTable, LootTableSeed)")
add("- Metody abstrakcyjne: getContainerSize(), getDefaultName(), createMenu()")
add("")
add("### 4.2 FridgeBlockEntity (cfm:fridge)")
add("- Rozmiar: 27 slotow (getContainerSize() = 27)")
add("- Menu: MenuType.GENERIC_9x3")
add("- Stan drzwi: onOpen() / onClose() ustawiaja FridgeBlock.OPEN i odtwarzaja dzwiek")
add("- NBT: Standardowe z BasicLootBlockEntity")
add("")
add("### 4.3 CabinetBlockEntity (cfm:cabinet)")
add("- Rozmiar: 18 slotow (getContainerSize() = 18)")
add("- Menu: MenuType.GENERIC_9x2")
add("- Stan drzwi: Ustawia CabinetBlock.OPEN")
add("- NBT: Standardowe")
add("")
add("### 4.4 FreezerBlockEntity (cfm:freezer)")
add("- Rozmiar: 3 sloty (source, fuel, result)")
add("- Mechanika: Zamrazanie uzywajac recept ModRecipeTypes.FREEZER_SOLIDIFY")
add("- Paliwo: Ice (2000 ticks), Packed Ice (18000), Blue Ice (162000)")
add("- Zmienne: fuelTime, fuelTimeTotal, freezeTime, freezeTimeTotal")
add("- NBT: FreezeTime, FreezeTimeTotal, FuelTime, RecipesUsedSize + RecipeLocation/RecipeAmount")
add("")
add("### 4.5 GrillBlockEntity (cfm:grill)")
add("- Inventory: WorldlyContainer")
add("  - fuel – 9 slotow na paliwo")
add("  - grill – 4 sloty na grillowane itemy")
add("- Mechanika: Grillowanie z przerzucaniem (flipped[])")
add("- Zmienne: cookingTimes[4], cookingTotalTimes[4], flipped[4], experience[4], rotations[4]")
add("- Recepty: ModRecipeTypes.GRILL_COOKING")
add("- NBT: Grill, Fuel, RemainingFuel, CookingTimes, CookingTotalTimes, Flipped, Experience, Rotations")
add("")
add("### 4.6 MailBoxBlockEntity (cfm:mail_box)")
add("- Rozmiar: 9 slotow")
add("- Rozszerza: BasicLootBlockEntity")
add("- Dane: UUID id, UUID ownerId, String name, String ownerName")
add("- Mechanika: serverTick() pobiera poczte z PostOffice")
add("- NBT: MailBoxUUID, MailBoxName, OwnerName, OwnerUUID")
add("")
add("### 4.7 KitchenSinkBlockEntity (cfm:kitchen_sink)")
add("- Rozszerza: FluidHandlerSyncedBlockEntity")
add("- Pojemnosc: FluidAttributes.BUCKET_VOLUME * 10 = 10 000 mB")
add("- NBT: Dane plynu przez FluidTank")
add("")
add("### 4.8 TrampolineBlockEntity (cfm:trampoline)")
add("- Dane: int count, DyeColor colour")
add("- Mechanika: updateCount() rekurencyjnie skanuje sasiadow (N/E/S/W) aby zliczyc polaczone trampoliny")
add("- NBT: Count, Color")
add("")
add("### 4.9 CoolerBlockEntity (cfm:cooler)")
add("- Rozmiar: 9 slotow")
add("- Menu: MenuType.GENERIC_9x1")
add("- Stan pokrywy: Ustawia CoolerBlock.OPEN")
add("- NBT: Standardowe")
add("")
add("### 4.10 DoorMatBlockEntity (cfm:door_mat)")
add("- Dane: String message")
add("- NBT: Message")
add("")
add("### 4.11 Pozostale BE (krotki opis)")
add("")
add("| BE | Rozmiar | Uwagi |")
add("|----|---------|-------|")
add("| BedsideCabinetBlockEntity | 9 slotow | Analogiczna do Cabinet |")
add("| DeskCabinetBlockEntity | 9 slotow | Analogiczna do Cabinet |")
add("| CrateBlockEntity | 9 slotow | Analogiczna do Cabinet |")
add("| KitchenDrawerBlockEntity | 9 slotow | Analogiczna do Cabinet |")

add("")
add("---")
add("")
add("## 5. Podsumowanie mapowania blokow 1.7.10 -> 1.18.2")
add("")
add("### 5.1 Bezposrednie mapowanie (ten sam lub podobny blok)")
add("")
add("| 1.7.10 Block ID | 1.18.2 Block ID | Uwagi |")
add("|-----------------|-----------------|-------|")
add("| tablewood | oak_table / spruce_table / ... | Mapowanie na podstawie metadanych drewna |")
add("| tablestone | stone_table / granite_table / ... | Mapowanie na podstawie metadanych kamienia |")
add("| chairwood | oak_chair / spruce_chair / ... | Jak wyzej |")
add("| chairstone | stone_chair / ... | Jak wyzej |")
add("| coffetablewood | oak_coffee_table / ... | Jak wyzej |")
add("| coffetablestone | stone_coffee_table / ... | Jak wyzej |")
add("| cabinet | oak_cabinet / spruce_cabinet / ... | Mapowanie na podstawie metadanych drewna |")
add("| bedsidecabinet | oak_bedside_cabinet / ... | Jak wyzej |")
add("| fridge | fridge_light / fridge_dark | Do ustalenia mapping jasny/ciemny |")
add("| freezer | freezer_light / freezer_dark | Do ustalenia mapping |")
add("| couch | white_sofa / orange_sofa / ... | Mapowanie metadanych koloru welny -> kolor sofy |")
add("| blinds | oak_blinds / ... | Mapowanie drewna |")
add("| curtains | oak_curtains / ... | Mapowanie drewna |")
add("| mailbox | oak_mail_box / ... | Mapowanie drewna |")
add("| hedge | oak_hedge / ... | Mapowanie typu lisci |")
add("| bin | Brak bezposredniego odpowiednika | Mozna zmapowac na oak_crate lub air |")
add("| stonepath | rock_path | Proste mapowanie |")
add("")
add("### 5.2 Bloki wymagajace decyzji (usuniete z 1.18.2)")
add("")
add("| 1.7.10 Block ID | Sugerowane mapowanie | Uzasadnienie |")
add("|-----------------|---------------------|--------------|")
add("| oven | air | Brak odpowiednika w 1.18.2 |")
add("| microwave | air | Brak odpowiednika |")
add("| computer | air | Brak odpowiednika |")
add("| printer | air | Brak odpowiednika |")
add("| tv | air | Brak odpowiednika |")
add("| stereo | air | Brak odpowiednika |")
add("| washingmachine | air | Brak odpowiednika |")
add("| dishwasher | air | Brak odpowiednika |")
add("| toilet | air | Brak odpowiednika |")
add("| basin | air | Brak odpowiednika (KitchenSink to osobny blok) |")
add("| bath1 / bath2 | air | Brak odpowiednika |")
add("| showerbottom / showertop | air | Brak odpowiednika |")
add("| showerheadoff / on | air | Brak odpowiednika |")
add("| wallcabinet | oak_cabinet? | Podobna funkcjonalnosc (szafka) |")
add("| birdbath | air | Brak odpowiednika |")
add("| tap | air | Brak odpowiednika |")
add("| electricfence | oak_upgraded_fence? | Podobna funkcja (ogrodzenie) |")
add("| doorbell | air | Brak odpowiednika |")
add("| firealarmoff / on | air | Brak odpowiednika |")
add("| ceilinglightoff / on | air | Brak odpowiednika |")
add("| lampon / lampoff | air | Brak odpowiednika |")
add("| tree | air | Brak odpowiednika |")
add("| present | air | Brak odpowiednika |")
add("| toaster | air | Brak odpowiednika |")
add("| blender | air | Brak odpowiednika |")
add("| plate | air | Brak odpowiednika |")
add("| cup | air | Brak odpowiednika |")
add("| choppingboard | air | Brak odpowiednika |")
add("| barstool | air | Brak odpowiednika |")
add("| cookiejar | air | Brak odpowiednika |")
add("| counterdoored | white_kitchen_counter? | Podobna funkcja (szafka kuchenna) |")
add("| countersink | white_kitchen_sink? | Podobna funkcja (zlew) |")
add("| kitchencabinet | white_kitchen_counter? | Podobna funkcja |")
add("| ovenoverhead | air | Brak odpowiednika |")
add("| whitefence | white_picket_fence? | Podobna funkcja (plot) |")
add("| hey / nyan / pattern / yellowglow / whiteglass | air lub zachowac jako dekoracyjne | Decyzja projektowa |")

add("")
add("### 5.3 Mapowanie Tile Entities -> Block Entities")
add("")
add("| 1.7.10 TE | 1.18.2 BE | Mapowanie inventory | Uwagi |")
add("|-----------|-----------|---------------------|-------|")
add("| cfmCabinet | cfm:cabinet | 16 -> 18 slotow | Bezposrednie mapowanie |")
add("| cfmFridge | cfm:fridge | 16 -> 27 slotow | Bezposrednie mapowanie |")
add("| cfmFreezer | cfm:freezer | Brak inventory -> 3 sloty | Zmiana architektury |")
add("| cfmBedsideCabinet | cfm:bedside_cabinet | 16 -> 9 slotow | Bezposrednie mapowanie |")
add("| cfmMailBox | cfm:mail_box | 6 -> 9 slotow | Dodatkowo UUID wlasciciela |")
add("| cfmCounterSink | cfm:kitchen_sink | Woda -> FluidTank | Zmiana systemu plynow |")
add("| cfmBin | cfm:crate? | 12 -> 9 slotow | Sugerowane mapowanie |")
add("| cfmWallCabinet | cfm:cabinet? | ~4-9 -> 18 slotow | Sugerowane mapowanie |")
add("| cfmCouch | (brak BE) | kolor -> metadata blockstate | Kolor w blockstate, nie BE |")
add("| cfmOven | (brak BE) | 18 slotow -> utrata | Brak odpowiednika |")
add("| cfmMicrowave | (brak BE) | 1 slot -> utrata | Brak odpowiednika |")
add("| cfmComputer | (brak BE) | 1 slot -> utrata | Brak odpowiednika |")
add("| cfmPrinter | (brak BE) | 3 sloty -> utrata | Brak odpowiednika |")
add("| cfmTV | (brak BE) | channel -> utrata | Brak odpowiednika |")
add("| cfmStereo | (brak BE) | record -> utrata | Brak odpowiednika |")
add("| cfmWashingMachine | (brak BE) | 5 slotow -> utrata | Brak odpowiednika |")
add("| cfmDishwasher | (brak BE) | 7 slotow -> utrata | Brak odpowiednika |")
add("| cfmBlender | (brak BE) | 4 sloty -> utrata | Brak odpowiednika |")
add("| cfmPlate | (brak BE) | itemy -> utrata | Brak odpowiednika |")
add("| cfmCup | (brak BE) | itemy -> utrata | Brak odpowiednika |")
add("| cfmChoppingBoard | (brak BE) | itemy -> utrata | Brak odpowiednika |")
add("| cfmCookieJar | (brak BE) | itemy -> utrata | Brak odpowiednika |")
add("| cfmPresent | (brak BE) | itemy -> utrata | Brak odpowiednika |")
add("| cfmBath | (brak BE) | woda -> utrata | Brak odpowiednika |")
add("| cfmBasin | (brak BE) | woda -> utrata | Brak odpowiednika |")
add("| cfmShowerHead | (brak BE) | woda -> utrata | Brak odpowiednika |")
add("| cfmToaster | (brak BE) | stan -> utrata | Brak odpowiednika |")
add("| cfmCabinetKitchen | cfm:kitchen_drawer? | 16 slotow -> 9 slotow | Sugerowane mapowanie |")
add("")
add("---")
add("")
add("## 6. NBT – kluczowe tagi do konwersji")
add("")
add("### 6.1 Tagi w 1.7.10 (Tile Entities)")
add("")
add("| TE | Kluczowe tagi NBT | Opis |")
add("|----|-------------------|------|")
add("| cfmOven | Items, BurnTime, CookTime | Inventory + stan gotowania |")
add("| cfmFridge | fridgeItems | Inventory (16 slotow) |")
add("| cfmCabinet | cabinetItems | Inventory (16 slotow) |")
add("| cfmFreezer | (brak unikalnych tagow) | Zalezny od lodowki |")
add("| cfmBedsideCabinet | (podobne do Cabinet) | Inventory |")
add("| cfmMailBox | mailBoxItems, OwnerUUID, OwnerName, Locked | Inventory + wlasciciel |")
add("| cfmComputer | StockNum | Stan handlu |")
add("| cfmPrinter | Items, PrintTime, PrintingTime | Inventory + drukowanie |")
add("| cfmTV | Channel | Kanal TV |")
add("| cfmStereo | RecordItem, Record, count | Plyta |")
add("| cfmMicrowave | Item, Coooking, Progress | Item + stan |")
add("| cfmBlender | Items, Blending, Progress, DrinkCount, DrinkName, HealAmount, CurrentRed/Green/Blue | Skomplikowany stan |")
add("| cfmWashingMachine | Items, Washing, SuperMode, Progress, Remaining | Zbroja + mydlo |")
add("| cfmDishwasher | Items, Washing, SuperMode, Progress, Remaining | Narzedzia + mydlo |")
add("| cfmBin | Items | Inventory (12 slotow) |")
add("| cfmCouch | Colour | Kolor sofy |")
add("| cfmToaster | (stan opiekania) | Boolean/progress |")
add("| cfmCounterSink | (stan wody) | Boolean |")
add("| cfmBasin | (stan wody) | Boolean/poziom |")
add("| cfmBath | (stan wody) | Boolean/poziom |")
add("| cfmPlate | Items | Jedzenie |")
add("| cfmCup | Items, (kolor) | Napoj |")
add("| cfmChoppingBoard | Items | Noz/skladniki |")
add("| cfmCookieJar | Items | Ciastka |")
add("| cfmPresent | Items | Prezent |")
add("| cfmShowerHead | (stan wody) | Boolean |")
add("| cfmWallCabinet | Items | Inventory |")

add("")
add("### 6.2 Tagi w 1.18.2 (Block Entities)")
add("")
add("| BE | Kluczowe tagi NBT | Opis |")
add("|----|-------------------|------|")
add("| cfm:cabinet | Items (ContainerHelper) | Inventory (18 slotow) |")
add("| cfm:fridge | Items | Inventory (27 slotow) |")
add("| cfm:freezer | Items, FreezeTime, FreezeTimeTotal, FuelTime, RecipesUsed | 3 sloty + zamrazanie |")
add("| cfm:bedside_cabinet | Items | Inventory (9 slotow) |")
add("| cfm:desk_cabinet | Items | Inventory (9 slotow) |")
add("| cfm:crate | Items | Inventory (9 slotow) |")
add("| cfm:mail_box | Items, MailBoxUUID, MailBoxName, OwnerName, OwnerUUID | 9 slotow + wlasciciel |")
add("| cfm:trampoline | Count, Color | Liczba polaczonych + kolor |")
add("| cfm:cooler | Items | Inventory (9 slotow) |")
add("| cfm:grill | Grill, Fuel, RemainingFuel, CookingTimes, CookingTotalTimes, Flipped, Experience, Rotations | 4+9 slotow + grillowanie |")
add("| cfm:door_mat | Message | Wiadomosc |")
add("| cfm:kitchen_sink | Tank (FluidTank) | Plyn (10 000 mB) |")
add("| cfm:kitchen_drawer | Items | Inventory (9 slotow) |")
add("")
add("### 6.3 Kluczowe roznice w NBT")
add("")
add("1. **Inventory format:**")
add("   - 1.7.10: Wlasne nazwy list (fridgeItems, cabinetItems) z custom slot tagami (fridgeSlot, cabinetSlot)")
add("   - 1.18.2: Standardowy Items list z Slot tagami (Minecraft standard)")
add("")
add("2. **UUID:**")
add("   - 1.7.10: OwnerUUID jako string")
add("   - 1.18.2: OwnerUUID jako int-array (Minecraft 1.16+ standard)")
add("")
add("3. **Plyny:**")
add("   - 1.7.10: Prosty boolean / poziom wody")
add("   - 1.18.2: FluidTank z pelnym NBT plynu (FluidName, Amount)")
add("")
add("4. **Kolor:**")
add("   - 1.7.10: int colour (0-15)")
add("   - 1.18.2: String Color (nazwa koloru) lub DyeColor enum")
add("")
add("---")
add("")
add("## 7. Wnioski i rekomendacje dla konwersji")
add("")
add("### 7.1 Prosta konwersja (direct mapping)")
add("")
add("1. Bloki dekoracyjne: Table, Chair, CoffeeTable, Cabinet, BedsideCabinet, Blinds, Curtains, Hedge, MailBox")
add("   - Wymagana konwersja metadanych drewna/kamienia/koloru na odpowiedni block ID w 1.18.2")
add("   - Wiele blokow z 1.7.10 nie ma metadanych (np. tablewood to tylko oak), wiec domyslne mapowanie na oak_table")
add("")
add("2. Fridge + Freezer:")
add("   - 1.7.10: Fridge (gora) + Freezer (dol) tworza wieloblok")
add("   - 1.18.2: Fridge (gora) + Freezer (dol) rowniez tworza wieloblok, ale z osobnymi BE")
add("   - BE Fridge: 16 -> 27 slotow (dodatkowe 11 slotow = puste)")
add("   - BE Freezer: nowy format 3-slotowy (source/fuel/result) – inventory z 1.7.10 Freezer nalezy wyslac do Fridge lub zrzucic na ziemie")
add("")
add("3. MailBox:")
add("   - Inventory: 6 -> 9 slotow")
add("   - UUID wlasciciela: string -> int-array")
add("   - Dodatkowe pola w 1.18.2: MailBoxUUID, MailBoxName – wygenerowac nowe UUID i nazwe z OwnerName")
add("")
add("### 7.2 Konwersja z utrata danych")
add("")
add("Dla blokow usunietych z 1.18.2 nalezy podjac decyzje:")
add("")
add("1. Inventory items (Oven, Microwave, Computer, Printer, TV, Stereo, WashingMachine, Dishwasher, Blender, Plate, Cup, ChoppingBoard, CookieJar, Present, WallCabinet, Bin):")
add("   - Opcja A: Zrzucic itemy na ziemie przy konwersji (drop items)")
add("   - Opcja B: Zmapowac na najblizszy odpowiednik (np. Bin -> Crate) i przeniesc itemy")
add("   - Opcja C: Calkowita utrata (items znikaja)")
add("")
add("2. Dane niematerialne (TV channel, Stereo record, Couch colour, Computer stockNum, Printer state, etc.):")
add("   - Te dane nie maja odpowiednika w 1.18.2 i zostana utracone")
add("")
add("3. Plyny (Basin, Bath, Shower, CounterSink):")
add("   - 1.7.10: Prosty boolean/poziom")
add("   - 1.18.2: Tylko KitchenSink ma BE z FluidTank")
add("   - Decyzja: Zmapowac CounterSink na KitchenSink i przeniesc stan wody?")
add("")
add("### 7.3 Decyzje do podjecia przez wlasciciela projektu")
add("")
add("1. Czy mapowac bin na crate czy zostawic air?")
add("2. Czy mapowac countersink na kitchen_sink?")
add("3. Czy mapowac wallcabinet na cabinet?")
add("4. Czy mapowac counterdoored / kitchencabinet na kitchen_counter / kitchen_drawer?")
add("5. Co zrobic z itemkami z usunietych blokow (Oven, Microwave, itp.) – drop czy utrata?")
add("6. Czy zachowac dekoracyjne bloki (hey, nyan, pattern, yellowglow, whiteglass) czy zamienic na air?")
add("7. Czy mapowac whitefence na white_picket_fence?")
add("8. Czy mapowac electricfence na oak_upgraded_fence?")
add("")
add("### 7.4 Kolejne kroki")
add("")
add("1. [Zadanie 2] Zbudowac tabele mappingu blockstate (1.7.10 metadata -> 1.18.2 block ID) dla blokow dekoracyjnych")
add("2. [Zadanie 3] Zaimplementowac konwerter inventory (NBT format 1.7.10 -> 1.18.2)")
add("3. [Zadanie 4] Obsluga wieloblokow (Fridge/Freezer, Bath, Shower)")
add("4. [Zadanie 5] Testowa konwersja malego fragmentu mapy i weryfikacja w swiecie 1.18.2")
add("")
add("---")
add("")
add("Raport wygenerowany automatycznie na podstawie analizy kodu zrodlowego MrCrayfish Furniture Mod 1.7.10 i 1.18.2.")
add("")

with open(out_path, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

size = os.path.getsize(out_path)
print(f"Zapisano raport: {out_path}")
print(f"Rozmiar: {size} bajtow")
