#Minecraft server properties
#Mon Feb 02 01:49:54 CET 2026
spawn-protection=0
generator-settings=
force-gamemode=false
allow-nether=true
gamemode=1
enable-query=false
player-idle-timeout=0
difficulty=1
spawn-monsters=true
op-permission-level=4
display-width=854
resource-pack-hash=
announce-player-achievements=true
pvp=true
snooper-enabled=true
level-type=DEFAULT
hardcore=false
enable-command-block=true
max-players=20
rcon.port=25577
server-port=25568
server-ip=
spawn-npcs=true
allow-flight=true
level-name=world_1710_no_mods
view-distance=10
resource-pack=
spawn-animals=true
white-list=false
rcon.password=test123
generate-structures=true
display-height=480
online-mode=false
max-build-height=256
level-seed=
enable-rcon=true
motd=Minecraft 1.7.10 Vanilla Server
